# Generated by Django 4.2.2 on 2023-07-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customercrm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
